Issue1 create page
flavas/flavas.github.io pull request #2
Opened 2016-10-01 09:47 UTC by imaramukuo

## チケット
create page#01
https://github.com/flavas/flavas.github.io/issues/1

## 概要
flavas仮ページを作成しました。
背景はグレーのままです。

## 期限
次回のactまで（2016/10/10）
宜しくお願いします！

2016-10-01 09:58 UTC, motokioomura commented on common.css
> +	background-color: #333;
てｓｔｇ

2016-10-01 10:03 UTC, motoki-oomura requested changes

2016-10-01 10:03 UTC, motokioomura commented on common.css
> +	background-color: #333;
カラーコードは6桁で。ほかもすべて同様。
また、bodyタグはあまりいじらず、直下にdivを設置してそこでスタイルを当てること。

2016-10-01 10:03 UTC, motokioomura commented on img/flavas.svg
> +<svg id="レイヤー_1" data-name="レイヤー 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 137.35 34"><defs><style>.cls-1{fill:#fff;}</style></defs><title>flavas</title><path class="cls-1" d="M183.89-88v0.3
ここのレイヤー１を変更してくださいな。
`id="レイヤー_1" data-name="レイヤー 1"`

2016-10-01 10:07 UTC, motokioomura commented
flavasの文字のところ、%ではなくpx指定で、media queryのタイミングで幅を小さくする方向でお願いします。

2016-10-08 06:53 UTC, motoki-oomura approved these changes

2016-10-08 06:53 UTC, motokioomura commented
マージします。

2016-10-08 06:53 UTC, merged